### ISSUE TITLE
Privacy and security

### ISSUE THREAD

**Issue by jcalfee** [GeeTeam/gt3-node-sdk#9]
Will this work if we host everything `gt.js` needs on a server for security and privacy?  We can proxy data to your API, I just want to make sure it does not contain data that would violate security or privacy.

I see you have your API endpoints in the `gt.js` source from the client:
https://github.com/GeeTeam/gt3-node-sdk/blob/master/demo/static/libs/gt.js#L37

But I also see you have an example that proxies the request from the server and an default `unknown` that implies that the client's IP address is not needed:
https://github.com/GeeTeam/gt3-node-sdk/blob/master/gt-sdk.js#L69

So I'm really not sure.  Thanks for clarifying..

**Comment by melvinren** [comment]
Do not need client's IP address.

**Comment by jcalfee** [comment]
> Do not need client's IP address.

Thank you, this is good to know.

Do you have English versions of the Captcha?

**Comment by melvinren** [comment]
the english demo: https://www.geetest.com/en/demo
you can set english image on our account site (http://gtaccount.geetest.com/)

**Comment by jcalfee** [comment]
Thanks .. Do you support loading your client-side libraries from the server?
